### ISSUE TITLE
Design API to filter on URI, source and dates

### ISSUE THREAD

**Issue by bertspaan** [erfgoed-en-locatie/histograph#12]
Design API to filter on URI, source and dates

**Comment by bertspaan** [comment]
Now supported:
- http://api.histograph.io/search?name=utrecht
- http://api.histograph.io/search?hgid=geonames/2758064
- http://api.histograph.io/search?uri=http://vocab.getty.edu/tgn/7271174
- http://api.histograph.io/search?name=amsterdam&type=hg:Municipality
  
  @phpetra @rutgervanwilligen new version of API should be deployed on server first

**Comment by phpetra** [comment]
Cool!

**Comment by reinvantveer** [comment]
Way to go!!!

Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Bert Spaan notifications@github.com
Datum:11-03-2015 21:41 (GMT+01:00)
Aan: histograph/api api@noreply.github.com
Cc:
Onderwerp: Re: [api] Design API to filter on URI, source and dates (#12)

Now supported:
-   http://api.histograph.io/search?name=utrecht
-   http://api.histograph.io/search?hgid=geonames/2758064
-   http://api.histograph.io/search?uri=http://vocab.getty.edu/tgn/7271174
-   http://api.histograph.io/search?name=amsterdam&type=hg:Municipality

@rutgervanwilligenhttps://github.com/rutgervanwilligen new version of API should be deployed on server first
