### ISSUE TITLE
Calling http://api.histograph.io/search?name=Bergen%20/%20Zoom

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#14]
Sending Bergen / Zoom to the api seems to timeout... why?

Should a client escape some characters?
http://api.histograph.io/search?name=Bergen / Zoom

**Comment by rutgervanwilligen** [comment]
http://stackoverflow.com/questions/1455578/characters-allowed-in-get-parameter

**Comment by bertspaan** [comment]
ab0730d346aaabed702370fff41d71cbbe470e94: API timeout fixed, and API now returns correct HTTP error codes.
