### ISSUE TITLE
Search for exact phrase - 'Gorinchem' should not find 'Sleewijck bij Gorinchem'

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#18]
When the api returns PiTs where just one word matches with the searchstring, obvious toponyms like Gorinchem return (too) many results. Difficult to standardize with.

**Comment by rutgervanwilligen** [comment]
Added to API in 4db3723. You can now specify exact search with `search?name=Gorinchem&exact=true` -- this will not return Sleewijck anymore.
