### ISSUE TITLE
POST to /sources results in an error without further explanation what went wrong

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#29]
Send in the request body was the following json:
{"id":"poorterding","title":"Carnaval onzin","description":"Bla die bla bla","license":"GPL","author":"@meme","website":"www.ergensheen.nl","edits":"ik heb er iets mee gedaan","editor":"Petra","sourceCreationDate":null}

Response: 400 [reason phrase] Bad Request
Why is this a bad request?

**Comment by phpetra** [comment]
PATCH does work, but POST does not

**Comment by bertspaan** [comment]
`null` is not a valid date (for `sourceCreationDate`). You should either submit a valid date, or remove the field altogether. But if I try a POST request with the same data, the API does return a error message:

``` json
{
    "message": [
        {
            "field": "data.sourceCreationDate",
            "message": "is the wrong type"
        }
    ]
}
```

**Comment by phpetra** [comment]
Allright, I'll not send null values anymore.
But empty strings is allowed?

**Comment by bertspaan** [comment]
Yes, they are allowed. But I can also make sure the API allows `null` values, if you want.

**Comment by phpetra** [comment]
No, don't bother ;)
