### ISSUE TITLE
What does the error 409 [reason phrase] Conflict mean?

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#31]
And why is it thrown?
I thought sources would be overwritten?

**Comment by bertspaan** [comment]
You cannot overwrite a source, but you can update it - with a PATCH request. If you try to create a source which already exists, the API returns 409, and an error message:

``` json
{
    "message": "Source 'poorterding' already exists"
}
```

**Comment by phpetra** [comment]
Ok
