### ISSUE TITLE
API accepts 0000-00-00 as a sourceCreationDate

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#32]
@bertspaan I'm not sure whether this is a bug, you decide ;)

**Comment by phpetra** [comment]
Ooh, see the carnaval source:
{

```
"author": "@NB",
"license": "GPL",
"description": "test van Petra",
"edits": "",
"website": "",
"editor": "",
"sourceCreationDate": "0000-00-00",
"title": "carnaval",
"id": "carnaval"
```

},

**Comment by bertspaan** [comment]
For now, let's say this is a feature.

Histograph accepts dates when they match `^-?([0-9]{1,4}|[0-9]{2})-([0]?[1-9]|[1][0-2])-([0]?[1-9]|[1|2][0-9]|[3][0|1])$|^$` :expressionless:
