### ISSUE TITLE
POST to /source/pits results in an ugly error on screen

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#33]
Call to the API:
POST /sources/carnaval/pits HTTP/1.1 Host: api.histograph.io Content-type: application/json Mime-type: application/x-ndjson Authorization: Basic aGlzdG9ncmFwaDpnM2gzMW1wNDU1 Accept: application/json User-Agent: Guzzle/5.2.0 curl/7.35.0 PHP/5.5.9-1ubuntu4.7 Content-Length: 30756 {"id":"carnaval\/1","name":"'t Aogje","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/2","name":"'t Bliekersriek","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/3","name":"'t Bokkerijersrijk","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/4","name":"'t Ganzedrp","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/5","name":"'t Heidurp","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/6","name":"'t Hout","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/7","name":"'t Hupke","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/8","name":"'t Kleigat","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/9","name":"'t Nlersriek","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/10","name":"'t Sanegat","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/11","name":"'t Ulenest","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/12","name":"'t Verkesriek","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/13","name":"'t Vosse'ol","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/14","name":"'t Zelfkantriek","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} 
    ...........truncated

Response is an ugly error:
HTTP/1.1 400 Bad Request Server: nginx/1.2.1 Date: Thu, 14 May 2015 10:01:42 GMT Content-Type: text/html; charset=utf-8 Content-Length: 600 Connection: keep-alive X-Powered-By: Express Access-Control-Allow-Origin: \* Vary: Origin X-Content-Type-Options: nosniff SyntaxError: Unexpected token {
   at Object.parse (native)
   at parse (/opt/histograph/io/node_modules/body-parser/lib/types/json.js:84:17)
   at /opt/histograph/io/node_modules/body-parser/lib/read.js:102:18
   at IncomingMessage.onEnd (/opt/histograph/io/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
   at IncomingMessage.g (events.js:180:16)
   at IncomingMessage.emit (events.js:92:17)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)

**Comment by bertspaan** [comment]
Ja, zag ik gister ook al... Inderdaad heel lelijk. Zit waarschijnlijk een fout in de JSON, en parsen van JSON zit nog vóór mijn foutafhandeling, ik moet mezelf daar nog even tussenwurmen. Ik kijk er morgen naar.

**Comment by phpetra** [comment]
Aah ja, ik probeerde net nog met wat simpelere json (slechts een paar regels maar gaat ook niet ...
Ligt het aand e manier waarop ik de ndjson stuur en kun jij wel POSTen? Of is het echt stuk (want dan ga ik lekker naar buiten, morgen is vroeg genoeg) ;-)

**Comment by bertspaan** [comment]
Ik kan 't wel. Je moet wel 'n PUT doen overigens, niet POST.

**Comment by bertspaan** [comment]
Maar ik moet dus in elk geval ook voor een goede foutmelding zorgen als je POST doet ipv. PUT en andersom!

**Comment by phpetra** [comment]
Ooh duh...
Ok, en mocht ik 'm als multipart form dingetjes sturen.. heeft ie dan nog een naam? "data" of "file" oid?

**Comment by bertspaan** [comment]
Ja, je moet 't bestand dan volgens mij `:source.pits.ndjson` of `:source.relations.ndjson` noemen, waar `:source` 't ID is van de bron. Dat moet ook nog in de API-documentatie...

**Comment by phpetra** [comment]
hmm PUT Gaat ook niet goed...ik test wel even met een oude carnaval.ndjson, als ik die kan vinden ;)

**Comment by bertspaan** [comment]
Wat zegt-ie?

**Comment by phpetra** [comment]
Hetzelfde eigenlijk, een parse error:

PUT /sources/carnaval/pits HTTP/1.1 Host: api.histograph.io Content-type: application/json Mime-type: application/x-ndjson Authorization: Basic aGlzdG9ncmFwaDpnM2gzMW1wNDU1 Accept: application/json User-Agent: Guzzle/5.2.0 curl/7.35.0 PHP/5.5.9-1ubuntu4.7 Content-Length: 1136 {"id":"carnaval\/264","name":"Zaandhaozenlaand","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/265","name":"Zaantaozelaant","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/266","name":"Zandhazendurp","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/267","name":"Zandkruiersland","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/268","name":"Zandkruiersland","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/269","name":"Zeikmeikenrijk","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/270","name":"Zeuvebultelaand","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/271","name":"Zwaajgat","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/272","name":"Zwammegat","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"} {"id":"carnaval\/273","name":"Zwetsgat","type":"hg:Place","hasBeginning":"2000-01-01","hasEnd":"2000-01-01"}

HTTP/1.1 400 Bad Request Server: nginx/1.2.1 Date: Thu, 14 May 2015 10:31:13 GMT Content-Type: text/html; charset=utf-8 Content-Length: 600 Connection: keep-alive X-Powered-By: Express Access-Control-Allow-Origin: \* Vary: Origin X-Content-Type-Options: nosniff SyntaxError: Unexpected token {
   at Object.parse (native)
   at parse (/opt/histograph/io/node_modules/body-parser/lib/types/json.js:84:17)
   at /opt/histograph/io/node_modules/body-parser/lib/read.js:102:18
   at IncomingMessage.onEnd (/opt/histograph/io/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
   at IncomingMessage.g (events.js:180:16)
   at IncomingMessage.emit (events.js:92:17)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13) We are sorry, but something went terribly wrong. Error Message: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON

**Comment by phpetra** [comment]
Dus ik vermoed dat er toch iets in die .ndjson niet helemaal goed is

**Comment by bertspaan** [comment]
Denk dat je de header `Content-type: application/json` ook moet veranderen in `application/x-ndjson`. Ik gebruik Express, HTTP-framework voor Node.js, en die doet automatisch al allemaal parsen van de body etc., aan de hand van 't Content-Type. En volgens mij is-ie best streng, en ik snap nog niet precies wat wel en wat niet mag.

**Comment by phpetra** [comment]
Yes! Dat was 'm!
Die had ik eerst zo staan met de POST maar toen kreeg ik een 404 (terecht natuurlijk)
Als het goed is hebben we nu nog maar 7 carnaval pits.... oid

**Comment by bertspaan** [comment]
Mooi! Note to self: API-documentatie uitbreiden, en ook mooie foutmelding als er goede data maar met verkeerd Content-Type binnenkomt.
