### ISSUE TITLE
The "van der werffstraat" in Leiden seems to be missing should be in nwb)

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#38]
I can't seem to find that street in Leiden and was wondering why??
http://histograph.io/viewer/#search=van%20der%20werffstraat

Is it not in the nwb? (it is an existing street)
Is it because of the search limit of 50?
In that case; why doesn't it show up when searching with quotes or limited on type? Or when exact=true?

http://histograph.io/viewer/#search=%22van%20der%20werffstraat%22%20&type=hg:Street

**Comment by bertspaan** [comment]
Well, it's the Van der Wer<b>f</b>straat. Just one f... :relieved: See [http://histograph.io/viewer/#search="van der werfstraat"](http://histograph.io/viewer/#search="van der werfstraat").

![image](https://cloud.githubusercontent.com/assets/1194896/7831861/df798e14-045a-11e5-84d7-f2a06f049a30.png)

**Comment by mmmenno** [comment]
I just figured it as well. But what we really really really need is search by boundingbox! In a mapviewer!. 

Then it's easy to just draw a rectangle and get all items (of the types you want), even when you do not know their exact spelling (or existence).

**Comment by phpetra** [comment]
Hmm that's funny, the ELO-people have written it down with two ff's .... oh joy

**Comment by mmmenno** [comment]
That shouldn't surprise you, by now ;-)

**Comment by bertspaan** [comment]
@mmmenno: geo/bounding box search is next on my list. It will be soon.
