### ISSUE TITLE
http://api.histograph.io redirects to http://erfgoedenlocatie.nl

### ISSUE THREAD

**Issue by reinvantveer** [erfgoed-en-locatie/histograph#39]
Just noticed: the blog-advertised web address of http://api.histograph.io redirects to http://erfgoedenlocatie.nl (instead of the probably intended https://api.histograph.io)

**Comment by bertspaan** [comment]
We are aware of this. API is now only accessible via HTTPS. I'm not sure whether calls http://api.histograph.io should redirect to https://api.histograph.io, we do not want users to supply credentials over plain HTTP... Maybe moved permanently? We will fix this issue once we move Histograph to its own server...

**Comment by reinvantveer** [comment]
Then maybe blog urls could be fixed? Otherwise there is no way of knowing where the demo api can be reached...

**Comment by bertspaan** [comment]
This is something Ralph should do.

**Comment by bertspaan** [comment]
I'll send him an e-mail.

**Comment by KitsR** [comment]
Yes, I also noticed this morning that it redirected, thanks for the correct URL. Changed all the URL-mentions on the blog. =Done
