### ISSUE TITLE
Relations don't show in API

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#43]
Right now, api only returns sameHgConcept relations. Would be very nice if api would also give isUsedFor, liesIn, absorbedBy and other relations!

**Comment by bertspaan** [comment]
I'm sure @wires will make this possible this week or next!

**Comment by mmmenno** [comment]
@bertspaan and I'm sure @wires would like to do so, but perhaps you could shed some light on how to accomplish this? It's not something that requires a complete rewrite of core functionality or something?

**Comment by bertspaan** [comment]
It does: right now, Core computes the [BFS](http://en.wikipedia.org/wiki/Breadth-first_search) of PITs matching your query - the BFS over `hg:sameHgConcept` is a Histograph Concept.

For this feature, we need to compute BFS first over `hg:sameHgConcept` relations first, and then, for each PIT, find all other outgoing/incoming relations.

This is not too difficult, but I don't want to add any code to Core before rethinking and rewriting a large part of it - we (@wires and I) will start doing this this week.

**Comment by wires** [comment]
I think this is implemented, plz. confirm and reopen if needed

https://github.com/histograph/neo4j-
plugin/blob/master/src/main/java/org/waag/histograph/plugins/ExpandConcepts.java#L54

not deployed, pending on https://github.com/histograph/deploy/issues/10
