### ISSUE TITLE
SameHgConcept relations don't come through

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#44]
In gemeentegeschiedenis-geometries relations are made to municipalities in the gemeentegeschiedenis dataset. Ndjson looks ok, but relations don't seem te be effectuated.

Gives very ugly results: searching for municipality Alkmaar now leads to 6 concepts instead of  1 concept containing 6 pits. See http://geothesaurus.nl/?q=alkmaar

**Comment by mmmenno** [comment]
@bertspaan and what about this one? Does it require a core rewrite as well? 

This one is somewhat more annoying, since it's out there in plain view

**Comment by bertspaan** [comment]
I don't know why this is happening - if `hg:sameHgConcept` relations are defined in NDJSON file, PITs should end up in one Histograph Concept. I'll need to look into this a bit deeper. If it's important, I can do this today.

**Comment by mmmenno** [comment]
It is important - it is hard enough to explain the difference between pits and concepts without search results like http://geothesaurus.nl/?q=alkmaar.

I'd be very happy if this is solved before the 18th. Also, i'm curious what caused it.

**Comment by bertspaan** [comment]
I'll look into it as soon as I can, and I'll make sure to solve this issue before the 18th!

**Comment by mmmenno** [comment]
Don't know why, but on the new server things are as they should be. So I'll close this one for now and reopen as soon as this behavior pops up with this or any other dataset.
