### ISSUE TITLE
api.erfgeo.nl does not accept POST request to the api

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#45]
When attempting to POST to /source I get the following error:

Oops, something went wrong. The API returned the following error: HTTP/1.1 401 Unauthorized Server: nginx/1.2.1 Date: Thu, 11 Jun 2015 09:28:09 GMT Content-Type: application/json; charset=utf-8 Content-Length: 36 Connection: keep-alive X-Powered-By: Express Access-Control-Allow-Origin: \* ETag: W/"24-f90624ee" {"message":"Authorization required"}

@wires @bertspaan  Can onen of you have a look or communicate the correct username/password?

**Comment by wires** [comment]
seems no pasword was set at all (`null`), I've setting it to `u/p=erfgeo/erfgeo` now. Please try again

**Comment by phpetra** [comment]
Nope, looks like same error:
Oops, something went wrong. The API returned the following error: HTTP/1.1 401 Unauthorized Server: nginx/1.2.1 Date: Thu, 11 Jun 2015 13:27:03 GMT Content-Type: application/json; charset=utf-8 Content-Length: 36 Connection: keep-alive X-Powered-By: Express Access-Control-Allow-Origin: \* ETag: W/"24-f90624ee" {"message":"Authorization required"}

@wires Maybe because it's not on https yet?

**Comment by wires** [comment]
Ditched the db, restarted everything. Think maybe user node was missing from neo? Anyway, importer works, which also uses auth, so in principle it works. plz try again

**Comment by phpetra** [comment]
jay!
Halfway there.... POST to /sources now worked.
POST to s/source/pits failed:
Oops, something went wrong. The API returned the following error: HTTP/1.1 422 Unprocessable Entity Server: nginx/1.2.1 Date: Thu, 11 Jun 2015 13:35:10 GMT Content-Type: application/json; charset=utf-8 Content-Length: 863 Connection: keep-alive X-Powered-By: Express Access-Control-Allow-Origin: \* ETag: W/"35f-8b0b887b" {"error":"NDJSON does not comply to schema","details":[{"line":1,"errors":[{"field":"data.type","message":"must be an enum value"},{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":2,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":3,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":4,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":5,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":6,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":7,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":8,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":9,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]},{"line":10,"errors":[{"field":"data.hasEnd","message":"pattern mismatch"}]}]}

What changed?
Same POST still works on the other API..?

**Comment by phpetra** [comment]
Okaah, waited a while, POST to /pits and /relations now seem to work, allthough the stuff is still in the queue.

Closing this.
