### ISSUE TITLE
Carnaval pits don't show up

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#46]
I've POSTed the carnaval set to the new API, waited for all queues to end, but I can't find any of the pits.
Why not?

They are all linked to tgn, so should be visible??
See:
http://api.erfgeo.nl/search?name=Brouwersgat
http://api.erfgeo.nl/search?name=Oeteldonk

**Comment by wires** [comment]
Not a bug, everything is imported but they have no geometry (so don't show up in API) and their relations are of the wrong type `isUsedFor`, must be `SAMEHGCONCEPT`.

![screen shot 2015-06-15 at 15 28 21](https://cloud.githubusercontent.com/assets/315734/8160977/e6408d4c-1373-11e5-8922-e6bc14e9829b.png)

**Comment by mmmenno** [comment]
Actually, `isUsedFor` happens to be the _right_ relationtype ;-) But since it's not possible to tell core and/or api to behave according to ontology before thursday, we'll use `sameHgConcept` relations for now!

**Comment by phpetra** [comment]
Ok, so now we know the exact problem... would it maybe be a good idea to create an issue for it? ;-)

**Comment by phpetra** [comment]
#refs https://github.com/histograph/core/issues/42
