### ISSUE TITLE
How can I find the groenesteeg in Leiden?

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#47]
@bertspaan Is it, or is it not possible atm to search for PiTs in PiTs? 
If possible, how? And for what data?
Please explain.
- "Amsterdam, Drenthe" is not working (yet?)
- nor is https://api.erfgeo.nl/search?name=groenesteeg&hg:liesIn=leiden

While https://api.erfgeo.nl/search?name=amsterdam&hg:liesIn=drenthe is working. What's the difference?

**Comment by wires** [comment]
Difference is what name you are looking for, nothing else.
Might be that there was no "groenesteeg" PIT with relations to leiden.

Seems to work now

![screen shot 2015-07-22 at 16 43 45](https://cloud.githubusercontent.com/assets/315734/8828143/e49fb6b8-3090-11e5-9161-09f8b2fe6cfb.png)
