### ISSUE TITLE
API fails for mysterious reason

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/histograph#52]
```
/home/histograph/api/lib/geojson.js:35
      features: json.map(function(concept) {
                     ^
TypeError: undefined is not a function
    at module.exports (/home/histograph/api/lib/geojson.js:35:22)
    at /home/histograph/api/index.js:44:26
    at /home/histograph/api/lib/query.js:35:11
    at Request._callback (/home/histograph/api/lib/graph.js:48:7)
    at Request.self.callback (/home/histograph/api/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/histograph/api/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/histograph/api/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by bertspaan** [comment]
Neo4j plugin returns incorrect JSON, probably because of memory error while traversing graph.

**Comment by wires** [comment]
`typeof` gives a string

the value of json is this:

```
[[{"pit":{"name":"Bergen","dataset":"geonames","id":"urn:hg:geonames:2759154","uri":"http://sws.geonames.org/2759154","type":"Place","geometry":{"type":"Point","coordinates":[4.70417,52.66917]},"data":{"featureClass":"P","featureCode":"PPL","countryCode":"NL","cc2":"NL","admin1Code":"07","admin2Code":"0373","admin3Code":"","admin4Code":""}},"relations":[{"to":"urn:hg:geonames:2759151","type":"liesIn"}],"hairs":[{"name":"Gemeente Bergen","id":"urn:hg:geonames:2759151","uri":"http://sws.geonames.org/2759151","type":"Municipality"}]}],[{"pit":{"name":"Bergen","dataset":"geonames","id":"urn:hg:geonames:3161732","uri":"http://sws.geonames.org/3161732","type":"Place","geometry":{"type":"Point","coordinates":[5.32415,60.39299]},"data":{"featureClass":"P","featureCode":"PPLA","countryCode":"NO","cc2":"","admin1Code":"07","admin2Code":"1201","admin3Code":"","admin4Code":""}},"relations":[],"hairs":[]}],[{"pit":{"name":"Bergen","dataset":"geonames","id":"urn:hg:geonames:2759155","uri":"http://sws.geonames.org/2759155","type":"Place","geometry":{"type":"Point","coordinates":[6.03333,51.6]},"data":{"featureClass":"P","featureCode":"PPL","countryCode":"NL","cc2":"","admin1Code":"05","admin2Code":"0893","admin3Code":"","admin4Code":""}},"relations":[{"to":"urn:hg:geonames:2759152","type":"liesIn"}],"hairs":[{"name":"Gemeente Bergen","id":"urn:hg:geonames:2759152","uri":"http://sws.geonames.org/2759152","type":"Municipality"}]}],[{"pit":{"name":"Bergen","dataset":"tgn","id":"urn:hg:tgn:7258872","uri":"http://vocab.getty.edu/tgn/7258872","type":"Place","geometry":{"type":"Point","coordinates":[6.033333,51.6]}},"relations":[{"to":"urn:hg:tgn:7003622","type":"liesIn"},{"to":"urn:hg:tgn:7003622","type":"liesIn"}],"hairs":[{"name":"Limburg","id":"urn:hg:tgn:7003622","uri":"http://vocab.getty.edu/tgn/7003622","type":"Province"},{"id":"urn:hg:tgn:7003622"
```

**Comment by wires** [comment]
we should handle this case and propagate the error to client

**Comment by ghost** [comment]
Any confirmation whether it's memory or something else? Happening to me too, but memory _seems_ ok.

**Comment by ghost** [comment]
or would the neo4j warning at startup: 'Max 1024 open files allowed, minimum of 40 000 recommended.' be relevant ...

**Comment by wires** [comment]
@hpfast new API is consistently failing due to out of memory issues (while importing a lot of memory is used, by both neo and elastic), I've asked for more memory on the machine

max files is not a problem, it is tweaked to about 100k on the server

the reason this issue is still open is because the API should report that there was an error on the backend

**Comment by ghost** [comment]
Ok. I encountered this on my own install. How much memory would you recommend?

**Comment by wires** [comment]
> On 04 Aug 2015, at 19:07, Hans Fast notifications@github.com wrote:
> 
> Ok. I encountered this on my own install. How much memory would you recommend?

around 2G minimum for neo and 1G min for elastic, node processes run around 200-400M each (core/api)

more = better (node/edge caches are very important for neo)

**Comment by ghost** [comment]
hmm. I just bumped total mem to 6GB and it's not maxing out at all. No imports are running, but all `/search` queries fail with either this error or `{"message":[{"field":"data","message":"no (or more than one) schemas match"}]}`

Do you get this structurally too? Are you sure it's memory?

fwiw.

**Comment by bertspaan** [comment]
`{"message":[{"field":"data","message":"no (or more than one) schemas match"}]}` is a not-so-descriptive error telling you that you should specify at least a search parameter: `q`, `name`, `uri` or `id`...

**Comment by bertspaan** [comment]
API should now return somewhat more useful errors: f5881cd4722d5ad2840fc8fafb735f13400c0ca7

**Comment by wires** [comment]
ahahah nice fix `| sed s/dit/dat/`

**Comment by wires** [comment]
![image](https://cloud.githubusercontent.com/assets/315734/9093441/7e0b6114-3bac-11e5-898b-77ccabe8340c.png)

w00t nice dat hij dit report

**Comment by phpetra** [comment]
Heel nice...;-P 
Vewarchten jullie hier binnenkort nog een oplossing voor te vinden?
Zoeken werkt nu helemaal niet?

**Comment by wires** [comment]
> On 07 Aug 2015, at 12:00, Petra Dreiskämper notifications@github.com wrote:
> 
> Heel nice...;-P 
> Vewarchten jullie hier binnenkort nog een oplossing voor te vinden?
> Zoeken werkt nu helemaal niet?

working on it, code van bert en hij is op vakantie, weet niet precies hoe/wat er mis gaat

**Comment by wires** [comment]
fixed

**Comment by phpetra** [comment]
Fijn!
En er staan ook al allerlei datasets in, zie ik nu?
(dacht dat wij die nog moesten doen?)
