### ISSUE TITLE
Cannot find pit by id

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/histograph#58]
search for http://vps662.directvps.nl:3000/search?q=braassemerstraat

get one hit, id = nwb/leiden-braassemerstraat ; no result http://vps662.directvps.nl:3000/search?id=nwb/leiden-braassemerstraat

input id param not passed through uri-normalizer?
`nwb/leiden-braassemerstraat ~> urn:hgid:nwb/leiden-braassemerstraat`

this works http://vps662.directvps.nl:3000/search?id=urn:hgid:nwb/leiden-braassemerstraat

**Comment by bertspaan** [comment]
Closed by 98e1a3a3c43b557b733eea45ef86e16ae9c002d0.
