### ISSUE TITLE
can't find pit by uri

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/histograph#59]
no hits for
http://vps662.directvps.nl:3000/search?uri=http://vocab.getty.edu/tgn/7271174

**Comment by bertspaan** [comment]
This is not because API doesn't find PITs by URI, but because this very URI is not downloaded by histograph-data's TGN module. See histograph/data#28.

Closed by 98e1a3a3c43b557b733eea45ef86e16ae9c002d0
