### ISSUE TITLE
schemas?

### ISSUE THREAD

**Issue by jobspierings** [erfgoed-en-locatie/histograph#64]
API specification refers to

> Histograph API has two endpoints:
> /search: geocoding, searching place names
> /datasets: dataset metadata
> /ontology: Histograph ontology
> /schemas: JSON schemasAPI specification (readme)
> /schemas: JSON schemas

But currently https://api.histograph.io/schemas gives 

> Cannot GET /schemas

**Comment by mmmenno** [comment]
See
- https://api.histograph.io/schemas/pits
- https://api.histograph.io/schemas/relations
- https://api.histograph.io/ontology
