### ISSUE TITLE
exact matching doesn't work

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/histograph#70]
weird

**Comment by phpetra** [comment]
Misschien ter aanvulling:

http://erfgeo.nl/thesaurus/#search=%22deventer%22&exact=true 
21 resultaten, met veel treffers "bij deventer"

http://erfgeo.nl/thesaurus/#search=%22bij%20deventer%22&exact=true
15 resultaten

dus met quotes zoeken en een spatie werkt op zich nog wel maar zonder spatie dus niet.
Want het idee was dat je bij zoeken op "Deventer" ook alleen treffers zou vinden die daar volledig aan voldoen (en dus niet "bij Deventer"

exact=true of exact=false lijkt geen enkel effect te hebben

Heb je er al naar kunnen kijken?
Want:
Amsterdam: 31 hits
Utrecht 16
Deventer 21
Bergen 45
