### ISSUE TITLE
geometry=simple parameter

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#71]
Parameter `geometry=false` makes api not return bandwidth-consuming geometries. Api should listen to `geometry=simple` as well and return only **point** geometries in that case.

People (seecr,rijksmuseum) seem to dislike polygons (let alone multipolygons) or just don't have a use for them.

**Comment by bertspaan** [comment]
@mmmenno @phpetra Added `simplify-geometry` parameter. When set to `true`, API uses https://github.com/Turfjs/turf-centroid to only return concept centroids.

**Comment by bertspaan** [comment]
(Not yet deployed. Tomorrow.)
