### ISSUE TITLE
index aanmaken met mapping werkt niet op amazon

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/histograph#72]
@bertspaan NOOIT ERRORS OPETEN

![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fchristopher.wendels.net%2Fwp-content%2Fuploads%2Fdelete-cookies-cookie-monster.jpg&f=1)

fix:
https://gist.github.com/wires/6aa3615cc99f47693fd5#file-default-mapping-js-L35

lowercase analyser was unknown..

![](https://gist.githubusercontent.com/wires/6aa3615cc99f47693fd5/raw/50e0e9a77985a54db742fc58b5edff7fdb5f6d85/Screen%2520Shot%25202015-10-22%2520at%252000.24.29.png)

**Comment by bertspaan** [comment]
:cry:

**Comment by wires** [comment]
So even though code has been added to `histograph/io` create the indices and their mappings before indexing the document, somehow (I suspect a race condition?...) this doesn't, sometimes a document is indexed before the index is created (and thus get's automatic mapping).

I've solved this for now by creating the indices in `histograph/core`, before bulk indexing.

This problem needs a better solution

**Comment by wires** [comment]
Actually, we now have this index creation in two places (here and `io`), needs to be removed

**Comment by wires** [comment]
I think this duplicate index creation is what is causing errors on AWS now

```
GRAPHMALIZER => 108 docs, 672.628264ms
Failed creating index
{ [Error: Bad Request] status: '400', message: 'Bad Request' } 'Bad Request'
Created all indices []
ES => 56 indexed, took 66ms, errors: false
```

**Comment by ghost** [comment]
I think this is affecting me too. Is solving this a question of removing it in one or the other place?

**Comment by wires** [comment]
no, it is a complicated race condition that is not easily fixed without changing how the API/IO/redis work. In the past we used the default-mapping file (described somewhere in the installation manual) that you place in the ES config directory. On AWS this is not possible so we changed the software to create the index. The `io` project manages the creation and deletion of datasets, which involves creating an elasticsearch index, but when PITs/relations are pushed to the dataset `io` places them on the redis queue and they end up in the Graphmalizer, which then indices them into ES and this implicitly creates an index. When the indices are already there you might see a problem in the console, but it shouldn't cause a problem.

**Comment by ghost** [comment]
> When the indices are already there you might see a problem in the
> console, but it shouldn't cause a problem.

ok, yeah, I saw that Graphmalizer was still proceeding. Maybe a false alarm
for me.

**Comment by wires** [comment]
> On 23 Nov 2015, at 14:47, Hans Fast notifications@github.com wrote:
> 
> > When the indices are already there you might see a problem in the
> > console, but it shouldn't cause a problem.
> 
> ok, yeah, I saw that Graphmalizer was still proceeding. Maybe a false alarm
> for me.

exactly, it’s probably a false alarm :^)

sorry for the confusion

**Comment by sbocconi** [comment]
Is this still an issue or is it resolved?

**Comment by bertspaan** [comment]
Still an issue.

**Comment by sbocconi** [comment]
We are running our own instance of ES, so the problem of the default mapping is not applicable anymore. As far as I can see there is no problem in creating the indexes
