### ISSUE TITLE
BAG ids for 'openbare ruimte' with type 'water' imported as hg:Street - see Rokin

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#75]
I wonder where BAG id 363300011950717 is coming from?

![image](https://cloud.githubusercontent.com/assets/4539618/10992373/80b9d646-8465-11e5-8df8-d67c7d8adb26.png)

**Comment by KitsR** [comment]
Quickly checked Kadaster BAG Viewer:

https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?objectId=0363300011950717
ID      0363300011950717
Naam  Rokin
Type   Water

https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?objectId=0363300000004410
ID      0363300000004410
Naam  Rokin
Type   Weg

**Comment by mmmenno** [comment]
Ah, right, couldn't find a way to search for BAG id at kadaster. Thanks ;-) 

Small but serious bug, though. Both Bagid's got type hg:Street during import. Same goes for Keizersgracht etc. People shouldn't use gracht id to standardize street!

**Comment by bertspaan** [comment]
Oplossing: alleen maar openbareruimtes van 't type straat opnemen in Histograph

**Comment by mmmenno** [comment]
Prima oplossing, maar ik durf niet te suggereren dat de BAG even opnieuw geïmporteerd moet worden...

**Comment by jobspierings** [comment]
@mmmenno 'nieuwe' BAG is geïmporteerd, kun je kijken of dit issue verholpen is?

**Comment by mmmenno** [comment]
Ik ga er naar kijken. Weet je toevallig of die voorloopnullen nu ook meegenomen zijn?

Groet!, Menno

**Comment by mmmenno** [comment]
Rokin looks fine, now:

![image](https://cloud.githubusercontent.com/assets/4539618/12302872/d3229ede-ba27-11e5-91ca-a446d30c59e4.png)

Keizersgracht and Prinsengracht give good results as well, so i'll close this issue!

**Comment by jobspierings** [comment]
@mmmenno leading zeroes has not been addressed - if relevant can you make a new issue? here I suppose https://github.com/histograph/data-bag.
