### ISSUE TITLE
Only BAG buildings with addresses in Histograph? Can't find bag/392100000038045

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#76]
bag/392100000038045 happens to be the Stadsdoelen in Haarlem, a rijksmonument (nr 19558) in which I attended a LOD conference with quite a crowd. And according to the Bagviewer, the building doesn't have an address.

Just curious - is this omission on purpose, maybe because most buildings without addresses are of little significance? Or is it a bug that should be fixed before someone feels like importing a brand new bag?

The building:
![image](https://cloud.githubusercontent.com/assets/4539618/11155026/22d23ad0-8a43-11e5-9156-dae41bb16a9e.png)

**Comment by KitsR** [comment]
Misschien ietwat off-topic hier, maar wel over gebruik en verwerken van de beschikbaar gestelde BAG-datasets: deze al gezien?
https://github.com/opengeogroep/NLExtract/pull/158

Via GitHub (https://github.com/opengeogroep/NLExtract) van NLExtract (http://www.nlextract.nl).

**Comment by bertspaan** [comment]
@mmmenno: This is on purpose, I only include buildings which contain _verblijfsobjecten_. Many buildings don't: schuurtjes, hokjes, dat soort gebouwen. Easy solution: create whitelist of buildings that should be added regardless.

**Comment by mmmenno** [comment]
That clarifies things. Let's see if this happens often or if this is just a freak incident and decide later. The thing with the Haarlem Stadsdoelen is - the building is now part of the Haarlem Public Library, which only has one address tied to the adjoining main building.
