### ISSUE TITLE
Not possible to retrieve buildings within polygon?

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#77]
With a query like [https://api.histograph.io/search?q=*&type=hg:Building&intersects={%20%22type%22:%20%22Polygon%22,%20%22coordinates%22:%20[%20[%20[%204.841451644897461,%2052.55720317521795%20],%20[%204.841451644897461,%2052.56153410085012%20],%20[%204.853382110595703,%2052.56153410085012%20],%20[%204.853382110595703,%2052.55720317521795%20],%20[%204.841451644897461,%2052.55720317521795%20]%20]%20]%20}](https://api.histograph.io/search?q=*&type=hg:Building&intersects={%20%22type%22:%20%22Polygon%22,%20%22coordinates%22:%20[%20[%20[%204.841451644897461,%2052.55720317521795%20],%20[%204.841451644897461,%2052.56153410085012%20],%20[%204.853382110595703,%2052.56153410085012%20],%20[%204.853382110595703,%2052.55720317521795%20],%20[%204.841451644897461,%2052.55720317521795%20]%20]%20]%20}) one expects to retrieve all buildings within the polygon.

It only returns buildings with a name (q=*). The api doesn't allow you to search without a q, uri or id parameter, and it cannot be an empty string. Regrettably, most buildings don't have names.

And there's another thing. I know there is a building named "De Arend" within this polygon, see for yourself on http://www.hicsuntleones.nl/erfgeoproxy/search/?q=menno/6 . It seems the intersects query is only done on **pits**, not concepts, with geometries.

Question: if I'm to make a leaflet app that shows alle streets, places, etc within it's bounding box (or at least the first 100), how am I going to make it show buildings? Since the [BAGviewer@Kadaster](https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html) broke (at least in my browsers), this functionality is much wanted!

**Comment by bertspaan** [comment]
API should allow the `q` parameter to be empty - then this problem will be solved. Easy fix!

**Comment by mmmenno** [comment]
Seems to work just fine now, thanks to @ocataco
