### ISSUE TITLE
Error starting node index.js: error creating Neo4j admin owner

### ISSUE THREAD

**Issue by reinvantveer** [erfgoed-en-locatie/histograph#78]
Creation of neo4j admin owner fails due to wrong (?) or lacking authentication?

```
reinv@lingui:~/data/Github/histograph/api$ node index.js 
   ●───────●    
  /║       ║\  
 / ║       ║ \ 
●  ║═══════║  ● 
 \ ║       ║ / 
  \║       ║/  
   ●───────●    
Histograph API listening at port 3001
Error creating Neo4j admin owner
```

and in my config.yml:

```
neo4j:                                      # Neo4j connection details + opt. authentication
  host: localhost
  port: 7474
  name: neo4j
  password: histograph
```

(I double-checked that I set the password correctly)

This is fixed by disabling authentication in neo4j-server.properties so basically disabling authentication is required for the stack to start. Which doesn't quite feel right...

**Comment by bertspaan** [comment]
I think `name` should be `user`, see https://github.com/histograph/installation#configuration-1

This should be documented better.

**Comment by reinvantveer** [comment]
Right, I expected the keys to be the same as for the api: name/password
configuration. The yaml config file itself could clarify that.

Thanks again, will post issues again soon :)

Op ma 4 jan. 2016 17:22 schreef Bert Spaan notifications@github.com:

**Comment by bertspaan** [comment]
I agree, this is confusing... :expressionless:

**Comment by sbocconi** [comment]
Hello,
I also have the same problem but since I am new I might be missing something.

My yml is:

```
api:
  dataDir: /Users/SB/Software/code/histograph/data
  admin:
    name: histograph
    password: password

neo4j:
  host: localhost
  port: 7474
  user: neo4j
  password: histograph

import:
  dirs:
    - /Users/SB/Software/code/erfgoed-en-locatie/data
```

if I set `dbms.security.auth_enabled=false` I do not get any error, otherwise I get the same error:

Error creating Neo4j admin owner

If I run the command from the web interface, it works although does not update any row:

```
$MERGE (admin:Owner { name:"neo4j" }) ON CREATE SET admin.password = "histograph"
(no changes, no rows)
```

if I look at the file `node_modules/histograph-io/lib/db.js` I think that the parameters read are the ones under api (config.api.admin.name; config.api.admin.password;):

```
module.exports.initAdmin = function() {
  // Create admin owner (if not exists)
  var name = config.api.admin.name;
  var password = config.api.admin.password;

  graphDb.cypher({
    query: 'MERGE (admin:Owner { name:{name} }) ON CREATE SET admin.password = {password}',
    params: {
      name: name,
      password: bcrypt.hashSync(password, 8)
    }
  }, function(err) {
    if (err) {
      console.error('Error creating Neo4j admin owner');
    }
  });
};
```

but even setting the variables does not work:

```
params: {
      name: 'neo4j',
      password: 'histograph'
    }
```

So I do not know...

**Comment by bertspaan** [comment]
I'll look into this.

**Comment by reinvantveer** [comment]
Changing 

``` yaml
name:
```

to

``` yaml
user:
```

got rid of the error message for me.

**Comment by wires** [comment]
Also keep in mind  that if you change this that `histograph-core` uses them to pass the credentials on to graphmalizer (https://github.com/histograph/core/blob/master/index.js#L174 ; it's currently set to `user`)

**Comment by sbocconi** [comment]
I still have this issue, I will look into it further.

**Comment by sbocconi** [comment]
It works, I just had the wrong password for Neo4j
