### ISSUE TITLE
Retrieve pits from dataset does not work in search?q=&dataset=nautz

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/histograph#81]
When i try to retrieve all (or 100 of them) pits from the recently uploaded dataset `nautz` i don't get any. Strange, because https://api.histograph.io/search?q=&dataset=bag works just fine and so does https://api.histograph.io/search?q=&dataset=menno and any other dataset i tried.

Any ideas why https://api.histograph.io/search?q=&dataset=nautz does not give any results? Strange thing is, https://api.histograph.io/search?q=poort&dataset=nautz works just fine.

**Comment by sbocconi** [comment]
The query now gives several results so I assume this does not apply anymore
